/**
 * OpenClaw HoneyAI — Main Orchestrator
 * Starts all enabled protocol honeypots and the management API.
 *
 * Usage:
 *   node server.js           # Uses config.yaml
 *   pnpm run setup            # Interactive setup wizard
 */

'use strict';

// Load .env if present (generated by setup wizard)
const fs   = require('fs');
const path = require('path');
const envPath = path.join(__dirname, '.env');
if (fs.existsSync(envPath)) {
    require('fs').readFileSync(envPath, 'utf8').split('\n').forEach(line => {
        const [k, ...v] = line.split('=');
        if (k && v.length) {
            let val = v.join('=').trim();
            if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
                val = val.substring(1, val.length - 1);
            }
            process.env[k.trim()] = val;
        }
    });
}


const config   = require('./core/config');
const { logger } = require('./core/logger');
const { readLastLinesSync } = require('./core/fileReader');

// ─── Banner ────────────────────────────────────────────────────────────────────
const chalk = require('chalk');

console.log(chalk.red.bold(`
  ██████╗ ██████╗ ███████╗███╗   ██╗ ██████╗██╗      █████╗ ██╗    ██╗
 ██╔═══██╗██╔══██╗██╔════╝████╗  ██║██╔════╝██║     ██╔══██╗██║    ██║
 ██║   ██║██████╔╝█████╗  ██╔██╗ ██║██║     ██║     ███████║██║ █╗ ██║
 ██║   ██║██╔═══╝ ██╔══╝  ██║╚██╗██║██║     ██║     ██╔══██║██║███╗██║
 ╚██████╔╝██║     ███████╗██║ ╚████║╚██████╗███████╗██║  ██║╚███╔███╔╝
  ╚═════╝ ╚═╝     ╚══════╝╚═╝  ╚═══╝ ╚═════╝╚══════╝╚═╝  ╚═╝ ╚══╝╚══╝
`));
console.log(chalk.yellow('  🍯 HoneyAI — AI-Powered Multi-Protocol Honeypot'));
console.log(chalk.gray(`  AI: ${config.ai.provider} → ${config.ai.url} (${config.ai.model})`));
console.log(chalk.gray(`  Reporting: ${getEnabledPlatforms(config.reporting)}`));
console.log('');

function getEnabledPlatforms(rep) {
    const platforms = ['abuseipdb','otx','dshield','blocklist_de','virustotal'];
    const active = platforms.filter(p => rep[p]?.enabled);
    return active.length ? active.join(', ') : chalk.red('none configured — run `pnpm run setup`');
}

// ─── Initialize global connection state ───────────────────────────────────────
global.activeConnections = {
    http: 0,
    ssh: 0,
    tarpit: 0,
    ftp: 0,
    telnet: 0,
    smtp: 0,
    mysql: 0,
    redis: 0,
    git: 0,
    vnc: 0,
    rdp: 0
};

// ─── Start all protocol honeypots ─────────────────────────────────────────────
logger.info('Starting OpenClaw HoneyAI...', { protocol: 'core' });

try { require('./protocols/http').start(); } catch (e) { logger.error(`HTTP failed to start: ${e.message}`); }
try { require('./protocols/ssh').start();  } catch (e) { logger.error(`SSH failed to start: ${e.message}`); }
try { require('./protocols/tcp').start();  } catch (e) { logger.error(`TCP failed to start: ${e.message}`); }

// ─── Management API ────────────────────────────────────────────────────────────
const express   = require('express');
const crypto    = require('crypto');
const mgmt      = express();
const MGMT_PORT = process.env.MGMT_PORT || 9999;
const MGMT_KEY  = process.env.HONEYAI_MGMT_KEY || crypto.randomBytes(32).toString('hex');

// Management API — localhost ONLY + API key auth (HIGH-02) + CORS denied (MED-06)
mgmt.use((req, res, next) => {
    const clientIp = req.socket.remoteAddress;
    if (clientIp !== '127.0.0.1' && clientIp !== '::1' && clientIp !== '::ffff:127.0.0.1') {
        return res.status(403).json({ error: 'Forbidden' });
    }
    // Block CORS preflight — no cross-origin access ever
    if (req.method === 'OPTIONS') {
        return res.status(403).end();
    }
    res.removeHeader('Access-Control-Allow-Origin');
    
    // Allow public access to root static assets (dashboard HTML/CSS/JS) and health check
    const publicPaths = ['/health', '/', '/index.html', '/favicon.ico'];
    const isPublic = publicPaths.includes(req.path) || req.path.startsWith('/assets/') || req.path.endsWith('.css') || req.path.endsWith('.js') || req.path.endsWith('.png') || req.path.endsWith('.jpg');
    
    if (!isPublic && req.headers['x-api-key'] !== MGMT_KEY) {
        return res.status(401).json({ error: 'Unauthorized' });
    }
    next();
});

mgmt.disable('x-powered-by');

// Serve static dashboard files
mgmt.use(express.static(path.join(__dirname, 'dashboard')));

mgmt.get('/health', (_, res) => res.json({ status: 'ok', uptime: Math.floor(process.uptime()), pid: process.pid }));

mgmt.get('/stats', (_, res) => {
    const eventsFile = config.logging.events_file;
    let events = [];
    try {
        events = readLastLinesSync(eventsFile, 2000)
            .map(l => { try { return JSON.parse(l); } catch { return null; } })
            .filter(Boolean);
    } catch (_) {}

    const byProto = {};
    const ipSet   = new Set();
    events.forEach(e => {
        byProto[e.protocol] = (byProto[e.protocol] || 0) + 1;
        if (e.ip) ipSet.add(e.ip);
    });

    res.json({
        total_events:   events.length,
        unique_ips:     ipSet.size,
        by_protocol:    byProto,
        last_event:     events[events.length - 1] || null,
        uptime_seconds: Math.floor(process.uptime())
    });
});

mgmt.get('/events', (req, res) => {
    const eventsFile = config.logging.events_file;
    const limit = Math.min(parseInt(req.query.limit) || 50, 500); // cap at 500
    let events = [];
    try {
        events = readLastLinesSync(eventsFile, limit)
            .map(l => { try { return JSON.parse(l); } catch { return null; } })
            .filter(Boolean);
    } catch (_) {}
    res.json(events);
});

// Cache CrowdSec decisions output for 30s to prevent CPU thrashing
let cachedDecisions = null;
let lastDecisionsFetch = 0;

mgmt.get('/sys', async (_, res) => {
    const { exec } = require('child_process');
    const now = Date.now();

    const fetchDecisions = async () => {
        if (process.env.CROWDSEC_BOUNCER_KEY) {
            try {
                const lapi = process.env.CROWDSEC_LAPI_URL || 'http://127.0.0.1:8080';
                const response = await fetch(`${lapi}/v1/decisions`, {
                    headers: { 'X-Api-Key': process.env.CROWDSEC_BOUNCER_KEY }
                });
                if (!response.ok) {
                    throw new Error(`CrowdSec LAPI responded with status: ${response.status}`);
                }
                return await response.json();
            } catch (err) {
                return { error: `LAPI fetch failed: ${err.message}` };
            }
        }

        return new Promise((resolve) => {
            exec('cscli decisions list -o json', (err, stdout) => {
                if (err) {
                    resolve({ error: err.message });
                } else {
                    try {
                        resolve(JSON.parse(stdout));
                    } catch (_) {
                        resolve({ raw: stdout.trim() });
                    }
                }
            });
        });
    };

    if (!cachedDecisions || (now - lastDecisionsFetch > 30000)) {
        cachedDecisions = await fetchDecisions();
        lastDecisionsFetch = now;
    }

    res.json({
        system: {
            cpu_usage: process.cpuUsage(),
            memory: process.memoryUsage(),
            uptime_seconds: Math.floor(process.uptime()),
            pid: process.pid
        },
        active_connections: global.activeConnections,
        crowdsec_decisions: cachedDecisions
    });
});

mgmt.listen(MGMT_PORT, '127.0.0.1', () => {
    logger.info(`Management API on :${MGMT_PORT} (localhost only, key: ${MGMT_KEY.substring(0, 8)}…)`, { protocol: 'core' });
});

// ─── Process resilience — don't crash on unhandled errors ─────────────────────
process.on('SIGTERM', () => { logger.info('Shutting down gracefully...'); process.exit(0); });
process.on('SIGINT',  () => { logger.info('Interrupted. Bye!'); process.exit(0); });

// Log but NEVER crash on uncaught exceptions — attackers must not be able to kill the honeypot
process.on('uncaughtException', (err) => {
    logger.error(`Uncaught exception (recovering): ${err.message}`);
    // Don't exit — honeypot stays alive
});

process.on('unhandledRejection', (reason) => {
    const msg = reason instanceof Error ? reason.message : String(reason);
    logger.warn(`Unhandled promise rejection (recovering): ${msg}`);
    // Don't exit
});
