/**
 * HoneyAI — Main Orchestrator
 * Starts all enabled protocol honeypots and the management API.
 *
 * Usage:
 *   node server.js           # Uses config.yaml
 *   pnpm run setup            # Interactive setup wizard
 */

'use strict';

// Load .env if present (generated by setup wizard)
const fs   = require('fs');
const path = require('path');
const envPath = path.join(__dirname, '.env');
if (fs.existsSync(envPath)) {
    require('fs').readFileSync(envPath, 'utf8').split('\n').forEach(line => {
        const [k, ...v] = line.split('=');
        if (k && v.length) {
            let val = v.join('=').trim();
            if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
                val = val.substring(1, val.length - 1);
            }
            process.env[k.trim()] = val;
        }
    });
}


const config   = require('./core/config');
const { logger } = require('./core/logger');
const { readLastLinesSync } = require('./core/fileReader');

// ─── Banner ────────────────────────────────────────────────────────────────────
const chalk = require('chalk');

console.log(chalk.red.bold(`
  ██╗  ██╗ ██████╗ ███╗   ██╗███████╗██╗   ██╗ █████╗ ██╗
  ██║  ██║██╔═══██╗████╗  ██║██╔════╝╚██╗ ██╔╝██╔══██╗██║
  ███████║██║   ██║██╔██╗ ██║█████╗   ╚████╔╝ ███████║██║
  ██╔══██║██║   ██║██║╚██╗██║██╔══╝    ╚██╔╝  ██╔══██║██║
  ██║  ██║╚██████╔╝██║ ╚████║███████╗   ██║   ██║  ██║██║
  ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝
`));
console.log(chalk.yellow('  🍯 HoneyAI — AI-Powered Multi-Protocol Honeypot'));
console.log(chalk.gray(`  AI: ${config.ai.provider} → ${config.ai.url} (${config.ai.model})`));
console.log(chalk.gray(`  Reporting: ${getEnabledPlatforms(config.reporting)}`));
console.log('');

function getEnabledPlatforms(rep) {
    const platforms = ['abuseipdb','otx','dshield','blocklist_de','virustotal'];
    const active = platforms.filter(p => rep[p]?.enabled);
    return active.length ? active.join(', ') : chalk.red('none configured — run `pnpm run setup`');
}

// ─── Initialize global connection state ───────────────────────────────────────
global.activeConnections = {
    http: 0,
    ssh: 0,
    tarpit: 0,
    ftp: 0,
    telnet: 0,
    smtp: 0,
    mysql: 0,
    redis: 0,
    git: 0,
    vnc: 0,
    rdp: 0,
    samba: 0,
    portscan: 0,
    httpproxy: 0,
    mssql: 0,
    snmp: 0,
    mcp: 0
};

// ─── Ollama health check (non-blocking) ───────────────────────────────────────
(async () => {
    try {
        const controller = new AbortController();
        const timeout = setTimeout(() => controller.abort(), 5000);
        const res = await fetch(`${config.ai.url}/api/tags`, { signal: controller.signal });
        clearTimeout(timeout);
        if (res.ok) {
            const data = await res.json();
            const models = (data.models || []).map(m => m.name);
            const hasModel = models.some(m => m.startsWith(config.ai.model));
            if (hasModel) {
                logger.info(`Ollama OK — model "${config.ai.model}" available`, { protocol: 'core' });
            } else {
                logger.warn(`Ollama reachable but model "${config.ai.model}" NOT found. Available: ${models.join(', ') || 'none'}`, { protocol: 'core' });
            }
        } else {
            logger.warn(`Ollama responded ${res.status} — AI responses will fall back to static`, { protocol: 'core' });
        }
    } catch (err) {
        logger.warn(`Ollama unreachable at ${config.ai.url} — AI responses will fall back to static. Error: ${err.message}`, { protocol: 'core' });
    }
})();

// ─── Start all protocol honeypots ─────────────────────────────────────────────
logger.info('Starting HoneyAI...', { protocol: 'core' });

try { require('./protocols/http').start(); } catch (e) { logger.error(`HTTP failed to start: ${e.message}`); }
try { require('./protocols/mcp').start();  } catch (e) { logger.error(`MCP failed to start: ${e.message}`); }
try { require('./protocols/ssh').start();  } catch (e) { logger.error(`SSH failed to start: ${e.message}`); }
try { require('./protocols/tcp').start();  } catch (e) { logger.error(`TCP failed to start: ${e.message}`); }
try { require('./protocols/samba').start(); } catch (e) { logger.error(`Samba failed to start: ${e.message}`); }
try { require('./protocols/portscan').start(); } catch (e) { logger.error(`Portscan failed to start: ${e.message}`); }
try { require('./protocols/httpproxy').start(); } catch (e) { logger.error(`HTTP Proxy failed to start: ${e.message}`); }
try { require('./protocols/mssql').start(); } catch (e) { logger.error(`MSSQL failed to start: ${e.message}`); }
try { require('./protocols/snmp').start(); } catch (e) { logger.error(`SNMP failed to start: ${e.message}`); }

// ─── Management API ────────────────────────────────────────────────────────────
const express   = require('express');
const crypto    = require('crypto');
const mgmt      = express();
const MGMT_PORT = process.env.MGMT_PORT || 9999;
const MGMT_KEY  = process.env.HONEYAI_MGMT_KEY || crypto.randomBytes(32).toString('hex');

// Management API — localhost ONLY + API key auth (HIGH-02) + CORS denied (MED-06)
mgmt.use((req, res, next) => {
    const clientIp = req.socket.remoteAddress;
    if (clientIp !== '127.0.0.1' && clientIp !== '::1' && clientIp !== '::ffff:127.0.0.1') {
        return res.status(403).json({ error: 'Forbidden' });
    }
    // Block CORS preflight — no cross-origin access ever
    if (req.method === 'OPTIONS') {
        return res.status(403).end();
    }
    res.removeHeader('Access-Control-Allow-Origin');
    
    if (req.path === '/health') {
        return next();
    }

    // Custom cookie parser
    const cookies = {};
    if (req.headers.cookie) {
        req.headers.cookie.split(';').forEach(c => {
            const parts = c.split('=');
            cookies[parts[0].trim()] = parts.slice(1).join('=').trim();
        });
    }

    const key = req.headers['x-api-key'] || req.query.key || cookies['honeyai-key'];
    
    if (key !== MGMT_KEY) {
        return res.status(401).send('Unauthorized');
    }

    // If key came from query parameter, set cookie and redirect to clean URL
    if (req.query.key) {
        res.setHeader('Set-Cookie', `honeyai-key=${MGMT_KEY}; Path=/; HttpOnly; SameSite=Strict`);
        return res.redirect(req.path);
    }

    next();
});

mgmt.disable('x-powered-by');

// Serve static dashboard files
mgmt.use(express.static(path.join(__dirname, 'dashboard')));

mgmt.get('/health', (_, res) => res.json({ status: 'ok', uptime: Math.floor(process.uptime()), pid: process.pid }));

mgmt.get('/stats', (_, res) => {
    const eventsFile = config.logging.events_file;
    let events = [];
    try {
        events = readLastLinesSync(eventsFile, 2000)
            .map(l => { try { return JSON.parse(l); } catch { return null; } })
            .filter(Boolean);
    } catch (_) {}

    const byProto = {};
    const ipSet   = new Set();
    events.forEach(e => {
        byProto[e.protocol] = (byProto[e.protocol] || 0) + 1;
        if (e.ip) ipSet.add(e.ip);
    });

    res.json({
        total_events:   events.length,
        unique_ips:     ipSet.size,
        by_protocol:    byProto,
        last_event:     events[events.length - 1] || null,
        uptime_seconds: Math.floor(process.uptime())
    });
});

mgmt.get('/events', (req, res) => {
    const eventsFile = config.logging.events_file;
    const limit = Math.min(parseInt(req.query.limit) || 50, 500); // cap at 500
    let events = [];
    try {
        events = readLastLinesSync(eventsFile, limit)
            .map(l => { try { return JSON.parse(l); } catch { return null; } })
            .filter(Boolean);
    } catch (_) {}
    res.json(events);
});

// Cache CrowdSec decisions output for 30s to prevent CPU thrashing
let cachedDecisions = null;
let lastDecisionsFetch = 0;

mgmt.get('/sys', async (_, res) => {
    const now = Date.now();

    const fetchDecisions = async () => {
        if (!process.env.CROWDSEC_BOUNCER_KEY) return null;
        try {
            const lapi = process.env.CROWDSEC_LAPI_URL || 'http://127.0.0.1:8080';
            // LOW #19: 5s timeout prevents /sys endpoint hanging if LAPI is unresponsive
            const controller = new AbortController();
            const timeout = setTimeout(() => controller.abort(), 5000);
            const response = await fetch(`${lapi}/v1/decisions`, {
                headers: { 'X-Api-Key': process.env.CROWDSEC_BOUNCER_KEY },
                signal: controller.signal
            });
            clearTimeout(timeout);
            if (!response.ok) {
                throw new Error(`CrowdSec LAPI responded with status: ${response.status}`);
            }
            return await response.json();
        } catch (err) {
            return { error: `LAPI fetch failed: ${err.message}` };
        }
    };

    if (!cachedDecisions || (now - lastDecisionsFetch > 30000)) {
        cachedDecisions = await fetchDecisions();
        lastDecisionsFetch = now;
    }

    res.json({
        system: {
            cpu_usage: process.cpuUsage(),
            memory: process.memoryUsage(),
            uptime_seconds: Math.floor(process.uptime()),
            pid: process.pid
        },
        active_connections: global.activeConnections,
        crowdsec_decisions: cachedDecisions
    });
});

mgmt.listen(MGMT_PORT, '127.0.0.1', () => {
    logger.info(`Management API on :${MGMT_PORT} (localhost only, key: ***)`, { protocol: 'core' });
});

// ─── Process resilience — don't crash on unhandled errors ─────────────────────
process.on('SIGTERM', () => { logger.info('Shutting down gracefully...'); process.exit(0); });
process.on('SIGINT',  () => { logger.info('Interrupted. Bye!'); process.exit(0); });

let crashCount = 0;

// Log but NEVER crash on uncaught exceptions — attackers must not be able to kill the honeypot
process.on('uncaughtException', (err) => {
    crashCount++;
    logger.error(`Uncaught exception #${crashCount} (recovering): ${err.message}\n${err.stack || '(no stack)'}`);
});

process.on('unhandledRejection', (reason) => {
    crashCount++;
    const msg = reason instanceof Error ? `${reason.message}\n${reason.stack || '(no stack)'}` : String(reason);
    logger.warn(`Unhandled rejection #${crashCount} (recovering): ${msg}`);
});
