#!/usr/bin/env node
/**
 * OpenClaw HoneyAI — Interactive Setup Wizard
 * Run: pnpm run setup
 * Asks for API keys and generates .env + config.yaml
 * NEVER commits .env or config.yaml to git.
 */

'use strict';

const readline = require('readline');
const fs       = require('fs');
const path     = require('path');
const yaml     = require('js-yaml');
const chalk    = require('chalk');

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
const ask = (q, def = '') => new Promise(res =>
    rl.question(chalk.cyan(`  ${q}`) + (def ? chalk.gray(` [${def}]`) : '') + chalk.cyan(': '), ans =>
        res(ans.trim() || def)
    )
);

async function main() {
    console.log(chalk.red.bold(`
╔══════════════════════════════════════════════════════╗
║     🍯 OpenClaw HoneyAI — Setup Wizard              ║
║     Configures AI engine + reporting platforms       ║
╚══════════════════════════════════════════════════════╝
`));
    console.log(chalk.yellow('  API keys will be saved to .env (gitignored, NEVER committed)\n'));

    // ── AI Engine ───────────────────────────────────────────────────────────
    console.log(chalk.white.bold('  ── AI Engine ──────────────────────────────────────────'));
    const aiProvider = await ask('AI provider (ollama / openai)', 'ollama');
    const aiUrl      = await ask('AI URL', aiProvider === 'ollama' ? 'http://localhost:11434' : 'https://api.openai.com');
    const aiModel    = await ask('Model name', aiProvider === 'ollama' ? 'qwen2.5:1.5b' : 'gpt-3.5-turbo');

    // ── Reporting Platforms ─────────────────────────────────────────────────
    console.log(chalk.white.bold('\n  ── Threat Intelligence Reporting (all optional) ───────'));
    console.log(chalk.gray('  Press Enter to skip any platform.\n'));

    const abuseipdb   = await ask('AbuseIPDB API key (https://www.abuseipdb.com/account/api)', '');
    const otxKey      = await ask('AlienVault OTX API key (https://otx.alienvault.com)', '');
    const otxSshPulse = otxKey ? await ask('  OTX SSH pulse ID', '') : '';
    const otxHttpPulse= otxKey ? await ask('  OTX HTTP pulse ID', '') : '';
    const dshieldKey  = await ask('SANS DShield API key (https://isc.sans.edu/myaccount.html)', '');
    const dshieldUser = dshieldKey ? await ask('  DShield user ID', '') : '';
    const blocklistKey= await ask('Blocklist.de API key (https://www.blocklist.de/en/api.html)', '');
    const blocklistEmail = blocklistKey ? await ask('  Blocklist.de email', '') : '';
    const vtKey       = await ask('VirusTotal API key (https://www.virustotal.com/gui/my-apikey)', '');

    // ── Notifications ───────────────────────────────────────────────────────
    console.log(chalk.white.bold('\n  ── Telegram Notifications (optional) ──────────────────'));
    const tgToken  = await ask('Telegram bot token (from @BotFather)', '');
    const tgChat   = tgToken ? await ask('  Telegram chat ID', '') : '';

    // ── Protocols ───────────────────────────────────────────────────────────
    console.log(chalk.white.bold('\n  ── Protocols to enable ─────────────────────────────────'));
    const enableSSH    = (await ask('Enable SSH honeypot? (y/n)', 'y')) === 'y';
    const enableHTTP   = (await ask('Enable HTTP honeypot? (y/n)', 'y')) === 'y';
    const enableFTP    = (await ask('Enable FTP honeypot? (y/n)', 'y')) === 'y';
    const enableTelnet = (await ask('Enable Telnet honeypot? (y/n)', 'y')) === 'y';
    const enableSMTP   = (await ask('Enable SMTP honeypot? (y/n)', 'y')) === 'y';
    const enableMySQL  = (await ask('Enable MySQL honeypot? (y/n)', 'y')) === 'y';
    const enableRedis  = (await ask('Enable Redis honeypot? (y/n)', 'y')) === 'y';
    const enableGit    = (await ask('Enable Git honeypot? (y/n)', 'y')) === 'y';
    const enableVNC    = (await ask('Enable VNC honeypot? (y/n)', 'y')) === 'y';
    const enableTarpit = (await ask('Enable SSH tarpit ports? (y/n)', 'n')) === 'y';

    rl.close();

    // ── Write .env ──────────────────────────────────────────────────────────
    const envLines = [
        `# OpenClaw HoneyAI — Environment Variables`,
        `# Generated by setup wizard on ${new Date().toISOString()}`,
        `# DO NOT COMMIT THIS FILE`,
        ``,
        `OLLAMA_URL=${aiUrl}`,
        `AI_MODEL=${aiModel}`,
        abuseipdb    ? `ABUSEIPDB_KEY=${abuseipdb}`             : '# ABUSEIPDB_KEY=',
        otxKey       ? `OTX_KEY=${otxKey}`                      : '# OTX_KEY=',
        dshieldKey   ? `DSHIELD_KEY=${dshieldKey}`              : '# DSHIELD_KEY=',
        blocklistKey ? `BLOCKLIST_KEY=${blocklistKey}`          : '# BLOCKLIST_KEY=',
        vtKey        ? `VT_KEY=${vtKey}`                        : '# VT_KEY=',
        tgToken      ? `TELEGRAM_TOKEN=${tgToken}`              : '# TELEGRAM_TOKEN=',
        tgChat       ? `TELEGRAM_CHAT=${tgChat}`                : '# TELEGRAM_CHAT=',
    ].join('\n');

    fs.writeFileSync(path.join(__dirname, '.env'), envLines + '\n');

    // ── Write config.yaml ───────────────────────────────────────────────────
    const configObj = {
        honeyai: { name: 'OpenClaw HoneyAI', version: '1.0.0' },
        ai: { provider: aiProvider, url: aiUrl, model: aiModel, timeout: 60000, temperature: 0.9 },
        protocols: {
            http:   { enabled: enableHTTP,   port: 8080 },
            ssh:    { enabled: enableSSH,    port: 2222, tarpit: enableTarpit, tarpit_ports: [222, 2200, 8022] },
            ftp:    { enabled: enableFTP,    port: 21 },
            telnet: { enabled: enableTelnet, port: 23 },
            smtp:   { enabled: enableSMTP,   port: 25 },
            mysql:  { enabled: enableMySQL,  port: 3306 },
            redis:  { enabled: enableRedis,  port: 6379 },
            git:    { enabled: enableGit,    port: 9418 },
            vnc:    { enabled: enableVNC,    port: 5900 }
        },
        reporting: {
            enabled:         true,
            cooldown_minutes: 60,
            abuseipdb:   { enabled: !!abuseipdb,    api_key: '' },
            otx:         { enabled: !!otxKey,        api_key: '', ssh_pulse_id: otxSshPulse, http_pulse_id: otxHttpPulse },
            dshield:     { enabled: !!dshieldKey,    api_key: '', user_id: dshieldUser },
            blocklist_de:{ enabled: !!blocklistKey,  api_key: '', email: blocklistEmail },
            virustotal:  { enabled: !!vtKey,         api_key: '' }
        },
        notifications: {
            telegram: { enabled: !!tgToken, bot_token: '', chat_id: '' }
        },
        logging: {
            level:        'info',
            file:         './logs/honeyai.log',
            events_file:  './logs/events.json'
        }
    };

    fs.writeFileSync(
        path.join(__dirname, 'config.yaml'),
        `# OpenClaw HoneyAI — Generated config (gitignored)\n` +
        `# API keys are in .env — this file is safe to share (no secrets)\n\n` +
        yaml.dump(configObj, { indent: 2 })
    );

    console.log(chalk.green.bold('\n  ✅ Setup complete!\n'));
    console.log(chalk.white('  Files created:'));
    console.log(chalk.gray('    .env          → API keys (gitignored, keep private)'));
    console.log(chalk.gray('    config.yaml   → Protocol config (gitignored)\n'));
    console.log(chalk.white('  Start the honeypot:'));
    console.log(chalk.yellow('    pnpm start\n'));
    console.log(chalk.white('  Run as system service:'));
    console.log(chalk.yellow('    sudo cp honey-ai.service /etc/systemd/system/'));
    console.log(chalk.yellow('    sudo systemctl enable --now honey-ai\n'));

    // ── Enabled platforms summary ────────────────────────────────────────────
    const platforms = {
        AbuseIPDB:    !!abuseipdb,
        OTX:          !!otxKey,
        DShield:      !!dshieldKey,
        'Blocklist.de': !!blocklistKey,
        VirusTotal:   !!vtKey,
        Telegram:     !!tgToken
    };
    console.log(chalk.white('  Reporting platforms:'));
    Object.entries(platforms).forEach(([name, on]) => {
        const icon = on ? chalk.green('✓') : chalk.gray('○');
        console.log(`    ${icon} ${name}`);
    });
    console.log('');
}

main().catch(e => { console.error(e.message); process.exit(1); });
