[Interface]
  PrivateKey = IseVUWnggGj7yl40dr03ULlpao0BU67H/zG4qfxVFok=
  Address = 192.168.123.107/32

[Peer]
  PublicKey = jwLCGRFC3a1OEblY4AGzRJ4iZDwWesjxE0LMoh9aUjY=
  AllowedIPs = 192.168.1.0/24
  Endpoint = 52.18.63.80:51820
  PersistentKeepalive = 270
